name-template: 'PSLab Version $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: ':rocket: Features and Enhancements'
    labels:
      - 'Feature'
      - 'Enhancement'
  - title: ':bug: Bug Fixes'
    label: 'Fix'
  - title: ':wrench: Maintenance'
    label: 'Chore'
  - title: ':page_facing_up: Documentation'
    label: 'Documentation'
change-template: '- $TITLE (#$NUMBER) - @$AUTHOR'
template: |-
    ## Changes
    $CHANGES

    This release was made possible thanks to $CONTRIBUTORS
